---
  - name: Running apt update
    apt:
      name: '*'
  - name: Installing Nginx
    apt:
      name: nginx
      state: present
  - name: Enabling Nginx
    systemd:
      name: nginx
      state: started
  - name: Updating Config file
    copy:
      src: "files/nginx.conf"
      dest: "/etc/nginx/conf.d/nginx.conf"
    register: config_updated
    notify: nginx_restart
